name: 'Notion Card x Pull Requests'
description: 'Link and update notion card base on pull requests'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node10'
  main: 'index.js'